name: Sync Labels across all repos

on:
  push:
    paths:
      - 'labels.yml'
  workflow_dispatch:             # allows manual trigger too

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: EndBug/label-sync@v2
        with:
          config-file: labels.yml
          delete-other-labels: false
          token: ${{ secrets.LABEL_SYNC_TOKEN }}
          repositories: |
            revoicechat/.github
            revoicechat/revoicechat
            revoicechat/ReVoiceChat-CoreServer
            revoicechat/ReVoiceChat-MediaServer
            revoicechat/ReVoiceChat-WebClient
            revoicechat/ReVoiceChat-i18n
